spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopper
    username: test_user
    password: Reds-2252!
  main:
    allow-circular-references: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    user: test_user
    password: Reds-2252!
    schemas: shopper
server:
  port: 8090