spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopper-io
    username: test_user
    password: Reds-2252!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    user: test_user
    password: Reds-2252!
    schemas: shopper-io
server:
  port: 8090